### ISSUE TITLE
Wrong result with absento

### ISSUE THREAD

**Issue by AlexKnauth** [gregr/icfp2017-artifact-auas7pp#4]
```
> (load "mk/mk.scm")
> (run 1 (q)
    (== q 'A)
    (absento q '(A)))
((A))

;; should be ()
;; wrongly produces ((A))
```

P.S.
If I rewrite it to use my own "not-membero" relation instead of absento, it produces the correct `()` result.

P.P.S
[webyrd/miniKenren-with-symbolic-constraints](https://github.com/webyrd/miniKanren-with-symbolic-constraints) seems to have the correct behavior on this example.

**Comment by gregr** [comment]
Hi @AlexKnauth , good observation.  This is a known issue.

The version of absento we use in this codebase only supports ground terms in the first argument.  It was originally defined this way in faster-miniKanren for performance, as this was the only usage pattern in the relational interpreter.

We don't believe it should cause problems to support a fully general absento, but we haven't tested it.  This is probably not the right repo to start changing its behavior.  https://github.com/michaelballantyne/faster-miniKanren is probably the right place to start.

**Comment by AlexKnauth** [comment]
If it is intentionally not supported, should be an error instead of a silent no-op?

**Comment by namin** [comment]
Yes, @webyrd first ever pull request does just that:
https://github.com/michaelballantyne/faster-miniKanren/pull/3
